### ISSUE TITLE
Clothes Physics

### ISSUE THREAD

**Issue by SakuraUO** [Loyalists/gflbo1#2]
Is it possible to implement clothes-based physics for all of the girls?

I thought it was funny, at first, but now I'm kinda annoyed by the fact that (most) cutscenes (and normal gameplay) you can see the girls undergarments most of the time.

**Comment by Loyalists** [comment]
This is not possible for old cod games, since clothes physics is not implemented into the engine at all (they are keyframed animations even if there are "clothes physics" in game).
